name: Check Lint and Scan Docker/Terraform Vulnerabilities

runs:
  using: composite
  steps:

    - name: Install Dependencies
      shell: bash
      run: | 
        set -euo pipefail
        sudo apt-get update -y && sudo apt-get install curl jq wget apt-transport-https gnupg lsb-release -y

    - name: Install Apps for Scan
      shell: bash
      run: | 
        # Install Hadolint
        curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint \
        && chmod +x /usr/local/bin/hadolint

        # Install Trivy
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

        # Terrascan
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Darwin_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
        install terrascan /usr/local/bin && rm terrascan && chmod +x /usr/local/bin/terrascan
        terrascan

    - name: Scan Docker
      shell: bash
      run: echo "Scan Docker"

    - name: Scan Terraform
      shell: bash
      run: echo "Scan Terraform"
